**Logistic regression project**

*Libraries uploading*

In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

*Data uploading*

In [5]:

data=pd.read_csv('Diabetes2.csv')
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

*data cleaning*

In [6]:

print(data.columns.tolist())

['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']


In [9]:
 #Convert DataFrame to NumPy array
data_array = data.to_numpy()
data_array


array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [10]:
X = data_array[:, :2]   
y = data_array[:, 2]  

In [11]:
X

array([[  6., 148.],
       [  1.,  85.],
       [  8., 183.],
       ...,
       [  5., 121.],
       [  1., 126.],
       [  1.,  93.]])

In [12]:

y = np.reshape(y, (-1, 1))

In [13]:
y

array([[ 72.],
       [ 66.],
       [ 64.],
       [ 66.],
       [ 40.],
       [ 74.],
       [ 50.],
       [  0.],
       [ 70.],
       [ 96.],
       [ 92.],
       [ 74.],
       [ 80.],
       [ 60.],
       [ 72.],
       [  0.],
       [ 84.],
       [ 74.],
       [ 30.],
       [ 70.],
       [ 88.],
       [ 84.],
       [ 90.],
       [ 80.],
       [ 94.],
       [ 70.],
       [ 76.],
       [ 66.],
       [ 82.],
       [ 92.],
       [ 75.],
       [ 76.],
       [ 58.],
       [ 92.],
       [ 78.],
       [ 60.],
       [ 76.],
       [ 76.],
       [ 68.],
       [ 72.],
       [ 64.],
       [ 84.],
       [ 92.],
       [110.],
       [ 64.],
       [ 66.],
       [ 56.],
       [ 70.],
       [ 66.],
       [  0.],
       [ 80.],
       [ 50.],
       [ 66.],
       [ 90.],
       [ 66.],
       [ 50.],
       [ 68.],
       [ 88.],
       [ 82.],
       [ 64.],
       [  0.],
       [ 72.],
       [ 62.],
       [ 58.],
       [ 66.],
       [ 74.],
       [ 8

*sigmoid function*

In [14]:
def sigmoid(z):
    return 1/(1+np.exp(-z))


*Cost function*

In [16]:
def costFunction(theta, X, y):
    m = np.size(y)
    hprime= X.dot(theta)
    h = sigmoid(hprime)
    j=-1/m*(np.log(h).T.dot(y)+np.log(1-h).T.dot(1-y))
    j_2=(-1/m)* np.sum(y*np.log(h)+(1-y)*np.log(1-h))
     
               
    if np.isnan(j[0]):
        return(np.inf)
    return(j[0])

*Gradient descent*

In [17]:

def gradient(theta, X, y):
    m = np.size(y)
    hprime=X.dot (theta)
    h = sigmoid (hprime)
    
    grad = (-1/m)*X.T.dot(h-y)
    #grad2=(-1/m)*

    return(grad.flatten())

In [18]:
initial_theta = np.zeros((X.shape[1],1))
cost = costFunction(initial_theta, X, y)
grad = gradient(initial_theta, X, y)
print('Cost: \n', cost)
print('Grad: \n', grad)

Cost: 
 [0.69314718]
Grad: 
 [ 272.99414062 8388.33398438]


In [19]:
def gradientDescent(X, y, theta=None, alpha=0.01, num_iters=50):
    if theta is None:
        theta = np.zeros((X.shape[1], 1))  # Automatically match number of features

    m = len(y)
    j_history = np.zeros(num_iters)

    for i in range(num_iters):
        h = sigmoid(X.dot(theta))
        gradient = (1 / m) * X.T.dot(h - y)
        theta = theta - alpha * gradient
        j_history[i] = (-1 / m) * np.sum(y * np.log(h) + (1 - y) * np.log(1 - h))

    return theta, j_history


In [20]:
theta, j_history = gradientDescent(X, y)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_2988\1428444463.py:12: RuntimeWarning: divide by zero encountered in log
  j_history[i] = (-1 / m) * np.sum(y * np.log(h) + (1 - y) * np.log(1 - h))
C:\Users\LENOVO\anaconda3\Lib\site-packages\numpy\_core\fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


In [21]:
theta

array([[ 135.55503512],
       [4164.54783203]])

*model prediction*

In [23]:
def predict_class(user_input, theta):
    if user_input.ndim == 1:
        user_input = user_input.reshape(1, -1)

    # Pas de biais ici
    prediction = sigmoid(user_input.dot(theta))
    return int((prediction >= 0.5)[0][0])

In [24]:

mon_input = np.array([45, 190])  
résultat = predict_class(mon_input, theta)
print("Prédiction :", résultat)

          

Prédiction : 1


In [25]:

mon_input = np.array([45, 190])  
résultat = predict_class(mon_input, theta)
print("Prédiction :", résultat)

          

Prédiction : 1
